### ISSUE TITLE
Sizzle的功能限制querySelectorAll都已经实现么?

### ISSUE THREAD

**Issue by chapgaga** [JSLite/JSLite#1]
问下:)

**Comment by yanhaijing** [comment]
jq的2.0以上版本也在向queryselectorall靠近，废弃了一些以前的选择器

**Comment by jaywcjlove** [comment]
有很多其实都可以废弃的，下面这个就要省不少代码的。
```js
document.body.classList.add('hasJS');
document.body.classList.remove('hasJS');
document.body.classList.toggle('hasJS');
document.body.classList.contains('hasJS');
```

**Comment by chapgaga** [comment]
@yanhaijing 这么说sizzle要死了么?

**Comment by yanhaijing** [comment]
@chapgaga 是的，因为在美国这种国家 ie8一下的占比已经很少了，所以只是时间问题，不存在sizzle要死的问题，sizzle也会与时俱进的

**Comment by chapgaga** [comment]
@yanhaijing sizzle的功能浏览器都有了,sizzle就没有存在的意义了啊

**Comment by yanhaijing** [comment]
任何事物都会变得没意义，只是时间问题

**Comment by chapgaga** [comment]
@yanhaijing 那不都要白学了么?

**Comment by jaywcjlove** [comment]
@chapgaga 没有白学哦，起码你学习了，选择器的使用和链式调用函数等各种牛逼的方法。入门简单，为你以后慢慢学会封装自己的库打好基础-_+

**Comment by chapgaga** [comment]
@jaywcjlove 你自己会写库么?

**Comment by chapgaga** [comment]
@jaywcjlove 学了这么久JQ,好多JQ方法没用过,你对JQ的所有方法都很熟悉么?

**Comment by jaywcjlove** [comment]
@chapgaga 写了很多简单的库，JSLite 就是我看很多遍jQuery 和zepto的产物哦。分享出来的有一些简单得  (cookie.js)[https://github.com/jaywcjlove/cookie.js] (store.js)[https://github.com/jaywcjlove/store.js]  (websocket)[https://github.com/jaywcjlove/websocket] 你可以看我的仓库，JSLite都实现了JQ很多方法，你说熟悉不？

**Comment by yanhaijing** [comment]
还可以看看我的github上的项目哦

**Comment by chapgaga** [comment]
@jaywcjlove 研究jq和zepto花了几年呢?

**Comment by jaywcjlove** [comment]
@chapgaga 研究它们要花几年？研究实现思路很重要，如果你js语法之类的还很生疏，那你有很长的路要走

**Comment by yanhaijing** [comment]
一周就差不多了吧

**Comment by yanhaijing** [comment]
主要是别人已经搞出来了，就不那么难了，第一次研究的话 肯定很费时间的

**Comment by chapgaga** [comment]
@jaywcjlove js基本语法挺熟悉了,一些不常用的语法还不属性,ecma规范啃起来很坑爹的样子
好多功能用不上,可是要自己写框架,这些细节估计要都懂才行啊:(
@yanhaijing 你研究过哪些框架呢?你的头像歪的,要不要帮你掰直了呢:)

**Comment by yanhaijing** [comment]
@chapgaga 这话听着 咋这么 郁闷呢，框架研究的不多:-)

**Comment by chapgaga** [comment]
@yanhaijing 亲现在项目是做库么?还是应用呢?

**Comment by yanhaijing** [comment]
库啊
