### ISSUE TITLE
最近发现   data  方法用得也是很多的希望可以加上

### ISSUE THREAD

**Issue by singod** [JSLite/JSLite#16]
最近发现   data  方法用得也是很多的 ，有时候发data  方法也是不可缺少的， 希望可以加上！

**Comment by yanhaijing** [comment]
这个方法有啊

**Comment by jaywcjlove** [comment]
@yanhaijing 以前就没有哦，我添加上去了

**Comment by yanhaijing** [comment]
嗯 data 其实就是 setattribute的语法糖而已 ，现在dataset的兼容性还不行

**Comment by jaywcjlove** [comment]
@yanhaijing  我也是这么理解的它只是一个语法糖...
