### ISSUE TITLE
hi 请问和zepto有什么区别？

### ISSUE THREAD

**Issue by yanhaijing** [JSLite/JSLite#3]

**Comment by jaywcjlove** [comment]
随着方法的增多，慢慢的zepto差别不大了，吸收了zepto与jQuery的实现方法，和理念，jQuery是一个类，会创建一个个实例，而zepto本身就只是一个对象。修复了zepto 约10几个bug，扩展了一些，我们在项目中常用的方法，甚至jQuery和zepto都是没有的。

**Comment by djyde** [comment]
那为什么不给 zepto PR

**Comment by jaywcjlove** [comment]
我希望自己能做得好一点点，我对英文有压力。至今英文还是要借助于翻译工具，混迹于IT界，还在成长中。

**Comment by wong2** [comment]
囧
