### ISSUE TITLE
map优化

### ISSUE THREAD

**Issue by jaywcjlove** [JSLite/JSLite#5]
使用Array的map优化map方法
```js
Array.prototype.map 
```

**Comment by jaywcjlove** [comment]
@yanhaijing 果然这样干不错哦，优化了。共同学习哦。

**Comment by yanhaijing** [comment]
:-) 我在看到这个方法时就觉得好奇怪，为何不用，测试这个得共同学习了，现在改了代码的话 没法保证对现有程序是否会引入bug

**Comment by jaywcjlove** [comment]
导致调用 `['after','prepend','before','append']` 方法报错 `TypeError: Argument 1 of Node.insertBefore does not implement interface Node.`

**Comment by yanhaijing** [comment]
回滚了
