### ISSUE TITLE
$(ele).on(event, selector, callback) selector error

### ISSUE THREAD

**Issue by yanhaijing** [JSLite/JSLite#6]
事件会绑定到ele上，但冒泡是没有做对selector的过滤，需添加从selector及其子节点的判断

**Comment by jaywcjlove** [comment]
😍

**Comment by yanhaijing** [comment]
修好了

**Comment by jaywcjlove** [comment]
@yanhaijing 测试过了没有问题哦 😄

**Comment by yanhaijing** [comment]
你是怎么测试的，测试用例 不同步吗

**Comment by jaywcjlove** [comment]
测试用例还没有研究透，我是原始测试方法....😢,Travis CI都没有玩儿转，有没有好的实例，发给我参考参考哦。共同学习学习嘛

**Comment by yanhaijing** [comment]
原始方法是指？？？

**Comment by jaywcjlove** [comment]
把写的各种例子跑一边。

**Comment by yanhaijing** [comment]
但是例子没有同步到仓库啊

**Comment by jaywcjlove** [comment]
@yanhaijing 研究了单元测试再上传啊。现在没有研究好怎么玩儿。~~~~(>_<)~~~~
