### ISSUE TITLE
Support index filter with function 'lt' and 'gt'

### ISSUE THREAD

**Issue by spinachx** [JSLite/JSLite#9]
Now, 'eq' works well, like boxUl.children().eq(1).removeAttr('draggable');
but 'lt' and 'gt' doesn't work.
I hope than can be supported.

**Comment by jaywcjlove** [comment]
@spinachx I plan to achieve "IT" and "GET" method . This plan may time a little longer.

**Comment by jaywcjlove** [comment]
@yanhaijing @spinachx 

### nextAll

```js
$("#box").nextAll("div")
```


### prevAll

```js
$("#box").prevAll("div")
```

**Comment by yanhaijing** [comment]
不是同一个概念 lt gt的概念是 过滤现在的集合，这个概念是重新选择dom

**Comment by jaywcjlove** [comment]
`:lt()` 是一个 jQuery 延伸出来的一个选择器 ， 并且不是的CSS规范的一部分, 使用`:lt()`查询不能充分利用原生DOM提供的 `querySelectorAll()` 方法来提高性能。为了在现代浏览器上获得更佳的性能，请使用 `$("your-pure-css-selector").slice(0, index)` 代替。

@spinachx

> array中提取的方法。从start开始，如果end 指出。提取不包含end位置的元素。
> `slice(start, [end]) ⇒ array`

```js
$("div").slice(3) //返回数组中第三个(包含第三个)之后的所有元素
$("div").slice(3,5) //返回数组 3-5之间的元素 
```
